/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as OllamaRouteImport } from './routes/ollama'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ExportRouteImport } from './routes/export'
import { Route as BoxesRouteImport } from './routes/boxes'
import { Route as BatteryRegulationsRouteImport } from './routes/battery-regulations'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OllamaRoute = OllamaRouteImport.update({
  id: '/ollama',
  path: '/ollama',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesRoute = BoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteryRegulationsRoute = BatteryRegulationsRouteImport.update({
  id: '/battery-regulations',
  path: '/battery-regulations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battery-regulations': typeof BatteryRegulationsRoute
  '/boxes': typeof BoxesRoute
  '/export': typeof ExportRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/ollama': typeof OllamaRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battery-regulations': typeof BatteryRegulationsRoute
  '/boxes': typeof BoxesRoute
  '/export': typeof ExportRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/ollama': typeof OllamaRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battery-regulations': typeof BatteryRegulationsRoute
  '/boxes': typeof BoxesRoute
  '/export': typeof ExportRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/ollama': typeof OllamaRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battery-regulations'
    | '/boxes'
    | '/export'
    | '/groups'
    | '/login'
    | '/ollama'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/battery-regulations'
    | '/boxes'
    | '/export'
    | '/groups'
    | '/login'
    | '/ollama'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/battery-regulations'
    | '/boxes'
    | '/export'
    | '/groups'
    | '/login'
    | '/ollama'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatteryRegulationsRoute: typeof BatteryRegulationsRoute
  BoxesRoute: typeof BoxesRoute
  ExportRoute: typeof ExportRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  OllamaRoute: typeof OllamaRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ollama': {
      id: '/ollama'
      path: '/ollama'
      fullPath: '/ollama'
      preLoaderRoute: typeof OllamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes': {
      id: '/boxes'
      path: '/boxes'
      fullPath: '/boxes'
      preLoaderRoute: typeof BoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battery-regulations': {
      id: '/battery-regulations'
      path: '/battery-regulations'
      fullPath: '/battery-regulations'
      preLoaderRoute: typeof BatteryRegulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatteryRegulationsRoute: BatteryRegulationsRoute,
  BoxesRoute: BoxesRoute,
  ExportRoute: ExportRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  OllamaRoute: OllamaRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
