version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      docker-actions:
        patterns:
          - 'docker/*'
          - 'actions/*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directories:
      - /apps/api
      - /apps/web
      - /apps/admin
    schedule:
      interval: weekly
