/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StickersRouteImport } from './routes/stickers'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as BoxesRouteImport } from './routes/boxes'
import { Route as BatteriesRouteImport } from './routes/batteries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsNewRouteImport } from './routes/items.new'
import { Route as ItemsIdRouteImport } from './routes/items.$id'
import { Route as BoxesIdRouteImport } from './routes/boxes.$id'

const StickersRoute = StickersRouteImport.update({
  id: '/stickers',
  path: '/stickers',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesRoute = BoxesRouteImport.update({
  id: '/boxes',
  path: '/boxes',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteriesRoute = BatteriesRouteImport.update({
  id: '/batteries',
  path: '/batteries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsNewRoute = ItemsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItemsRoute,
} as any)
const BoxesIdRoute = BoxesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BoxesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batteries': typeof BatteriesRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/stickers': typeof StickersRoute
  '/boxes/$id': typeof BoxesIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/new': typeof ItemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batteries': typeof BatteriesRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/stickers': typeof StickersRoute
  '/boxes/$id': typeof BoxesIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/new': typeof ItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batteries': typeof BatteriesRoute
  '/boxes': typeof BoxesRouteWithChildren
  '/items': typeof ItemsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/scan': typeof ScanRoute
  '/stickers': typeof StickersRoute
  '/boxes/$id': typeof BoxesIdRoute
  '/items/$id': typeof ItemsIdRoute
  '/items/new': typeof ItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batteries'
    | '/boxes'
    | '/items'
    | '/login'
    | '/profile'
    | '/scan'
    | '/stickers'
    | '/boxes/$id'
    | '/items/$id'
    | '/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batteries'
    | '/boxes'
    | '/items'
    | '/login'
    | '/profile'
    | '/scan'
    | '/stickers'
    | '/boxes/$id'
    | '/items/$id'
    | '/items/new'
  id:
    | '__root__'
    | '/'
    | '/batteries'
    | '/boxes'
    | '/items'
    | '/login'
    | '/profile'
    | '/scan'
    | '/stickers'
    | '/boxes/$id'
    | '/items/$id'
    | '/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatteriesRoute: typeof BatteriesRoute
  BoxesRoute: typeof BoxesRouteWithChildren
  ItemsRoute: typeof ItemsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ScanRoute: typeof ScanRoute
  StickersRoute: typeof StickersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stickers': {
      id: '/stickers'
      path: '/stickers'
      fullPath: '/stickers'
      preLoaderRoute: typeof StickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes': {
      id: '/boxes'
      path: '/boxes'
      fullPath: '/boxes'
      preLoaderRoute: typeof BoxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batteries': {
      id: '/batteries'
      path: '/batteries'
      fullPath: '/batteries'
      preLoaderRoute: typeof BatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/new': {
      id: '/items/new'
      path: '/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof ItemsNewRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/boxes/$id': {
      id: '/boxes/$id'
      path: '/$id'
      fullPath: '/boxes/$id'
      preLoaderRoute: typeof BoxesIdRouteImport
      parentRoute: typeof BoxesRoute
    }
  }
}

interface BoxesRouteChildren {
  BoxesIdRoute: typeof BoxesIdRoute
}

const BoxesRouteChildren: BoxesRouteChildren = {
  BoxesIdRoute: BoxesIdRoute,
}

const BoxesRouteWithChildren = BoxesRoute._addFileChildren(BoxesRouteChildren)

interface ItemsRouteChildren {
  ItemsIdRoute: typeof ItemsIdRoute
  ItemsNewRoute: typeof ItemsNewRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsIdRoute: ItemsIdRoute,
  ItemsNewRoute: ItemsNewRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatteriesRoute: BatteriesRoute,
  BoxesRoute: BoxesRouteWithChildren,
  ItemsRoute: ItemsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ScanRoute: ScanRoute,
  StickersRoute: StickersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
